name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: cache
        uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles(format('{0}{1}', github.workspace, '/package.json')) }}

      - name: build and deploy
        run: |
          npm install
          npm run deploy -- --repo=https://github.com/swfz/ngx-libraries.git --name="$GITHUB_USERNAME" --email="$GITHUB_EMAIL"
        env:
          CI: true
          GH_TOKEN: ${{secrets.GITHUB_PERSONAL_TOKEN}}
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_EMAIL: ${{ secrets.GITHUB_EMAIL }}

  notification:
    name: slack notification
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      - uses: actions/checkout@v1
      - name: slack notification
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: ${{ job.name }}
          fields: repo,message,action,author,workflow,ref
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

